### ISSUE TITLE
특정 상황에서 아스키값 + 1이 보여지는 버그 리포트

### ISSUE THREAD

**Issue by kdh93** [byungmeo/GersangStation#11]
MOTP 값 입력, 
설정 탭의 계정 설정, 
클라이언트 설정 

에서 영문, 숫자, 특수 문자 등 아스키 값으로 표현가능한 텍스트를 입력하면

아스키값 + 1 의 값이 표시가 되지만 저장되는 값은 표시되는 값이 아니라 원래 입력했던 값으로 저장됩니다. 

하지만 아스키값으로 표현 불가능한 한글 등의 텍스트는 입력할때 문제가 없습니다. 
또한 한글 + 영문, 숫자, 특수문자 를 입력할 경우 계정목록, 메인탭의 드롭다운 목록의 표시에서도 아스키값 + 1이 표기되지만
메인 탭에서 선택 후에는 정상적인 입력값이 표기됩니다. 

해당 버그에 대한 예시 이미지는 따로 첨부하였습니다. 

![거상스테이션_오류](https://user-images.githubusercontent.com/44677957/184470330-8c6c9ae0-efba-44ce-b14b-055a23985c15.jpg)
![거상스테이션_오류2](https://user-images.githubusercontent.com/44677957/184470401-0eaeba2f-b24c-4df9-a6b0-ae529a4cef56.jpg)
![거상스테이션_오류3](https://user-images.githubusercontent.com/44677957/184470487-fd6a7d73-a4ad-4e6b-a355-40dc7e337679.jpg)

**Comment by byungmeo** [comment]
안녕하세요 해결 방법은 #9 를 참고해주세요.
제 프로그램에서 쓰고 있는 MaterialSkin 이라는 라이브러리의 문제라서
Roboto 폰트 설치 문제라는것 빼고는 저도 자세히 원인을 파악하지 못하고 있는 상태입니다..

다시 한 번 문의를 할 예정이며,
우선은 문의 주시는 분들한테는 폰트 삭제 하는 방향으로 안내를 해드리고 있고
폰트를 강제로 삭제 시키는 방안도 고려해 보았으나 여러 이유로 쉽지 않아 보이네요..

그래도 Roboto 폰트가 필요하신 분들도 있을 수 있으니
최대한 삭제하지 않아도 될 수 있도록 해결방법을 찾아보겠습니다 ㅠ

**Comment by byungmeo** [comment]
1.5.0 버전에서 해결 될 예정입니다.
