### ISSUE TITLE
Hidpi 적용에 관한 건

### ISSUE THREAD

**Issue by chlrhkd4** [byungmeo/GersangStation#31]
@chlrhkd4
아래에 말씀하신대로 전부 material control로 교체하게 되면, 
dpi설정을 dpiUnaware 가 아닌 다른 모드로 교체하기 편하게 될것같은데 고려 부탁드립니다. 
참고로 dpi세팅 변경시 향상된 창모드 코드에도 조그마한 변경이 필요함니다

번외로 폰트 관련한 문제가 notoSans 브랜치에서 해결되었고
기존에 폰트 문제 때문에 사용했던 CustomControl 들을 전부 MaterialControl로 교체 하는 작업을 진행 중입니다.

아마 무결성 검사 기능 건이 마무리되는대로 1.5 버전 릴리즈가 이루어질 것 같은데
혹시나 그 전에 릴리즈 버전 사용을 원하시면
아래처럼 설정하시고 publish 후 사용하시면 될 것 같습니다.

![image](https://github.com/byungmeo/GersangStation/assets/37506142/2c9b69ad-9703-4dae-9081-a2be554f051f)

자동 업데이트 다운로드 기능이 없는 만큼 가능한 패치를 몰아서 하는 편이라
양해 부탁드립니다 ㅎㅎ..

_Originally posted by @byungmeo in https://github.com/byungmeo/GersangStation/issues/29#issuecomment-1750746851_

**Comment by byungmeo** [comment]
직접 적용해본 결과 그렇게 만족스럽지가 않아서
조금 뭉게지더라도 기존 모드 그대로 두는게 좋을 것 같습니다 ㅠㅠ
일단 UI 라이브러리 자체적으로도 Dpi 모드 관련 겹침 버그가 있고
Dpi에 따라 창 크기가 확장되면서 안에 컨트롤들의 간격이나 이런 것들도
멀어지는데 이 때도 예쁘게 보이려면 생각보다 많은 노력이 필요할 것 같습니다.
