### ISSUE TITLE
.editorconfig 파일 관련

### ISSUE THREAD

**Issue by chlrhkd4** [byungmeo/GersangStation#33]
`안녕하세요.`

혹시 사용하시는 .editorconfig파일을 깃허브에 같이 업로드 해주실 수 있으실까요?

솔루션 설정에 보면
```
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

```
이와 같이 되어있어서, 상위 폴더에 있는 .editorconfig파일을 참조하는 것 같은데, 제가 코드를 받았을때는 존재하지 않아서, 계속 줄바꿈이나 여러가지 쓸데없는 변경이 이루어지는 것 같습니다.

**Comment by byungmeo** [comment]
아하 코딩 컨벤션 말씀하시는거죠?
지금까지 혼자 하다 보니까 이런거 신경을 못썼네요..
오랫동안 만진 코드다보니 뒤죽박죽이 있긴 한데
지금 master 쪽에 올라간게 제가 쓰는 규칙입니다.
솔루션 설정이랑 연관이 있는지는 잘 모르겠네요.
여전히 안되시면 말씀주세요!
