### ISSUE TITLE
ClipMouse 개선

### ISSUE THREAD

**Issue by byungmeo** [byungmeo/GersangStation#34]
방법 찾기
브랜치 ClipMouse

1. 선택한 클라만 마우스 가두기
2. 거상 활성화 시 F11 먹통 해결
3. 타 게임 실행 중 거상 마우스 가두기 먹통
4. 단축키 변경

**Comment by byungmeo** [comment]
@chlrhkd4 

제가 생각한건
모든 클라 가두기와
선택 클라 가두기를 분리해서
선택 클라 가두기 활성화 후 처음으로 잡히는 Gersang 프로세스 핸들을 기준으로
가두기를 수행하는걸 생각했습니다.

제가 더 정확하게 알아보진 않았지만
클라설정에서 원하는 클라 설정해도
GersangStation -> GersangStarter -> Gersang
이런식으로
GersangStarter 라는 친구를 거쳐서 Gersang이 실행되는 방식이라
프로세스 잡기가 좀 까다로운 느낌이 있었습니다.
GersangStarter 프로그램 자체가 까보는게 워낙 쉬워서
아예 GersangStarter 역할을 대신하는 방안이 있기는 한데
이건 가끔 Starter가 업데이트 되기도 해서
유지보수나 저작권, 신뢰성 측면에서도 조금 난처하더라구요.

**Comment by byungmeo** [comment]
@chlrhkd4 

user32.dll 불러올 때 system32에 user32.dll이 있는데도 
System.IO.FileNotFoundException 예외가 발생하는 분들이 계시네요

![image](https://github.com/byungmeo/GersangStation/assets/37506142/17109799-5eef-4350-aa34-5eb7447989b7)

예외 메시지가 좀 빈약해서 어떤 문제인지 몰랐는데
1.4.2는 잘 된다 하니 아마 DllImport 문제가 아닌가 싶습니다..
환경 변수도 문제 없었고
혹시 몰라 user32.dll을 거상스테이션 폴더에 놓아보았는데도 큰 효과는 없네요.

혹시 이 문제에 대해 알고 계신게 있으신가요?

**Comment by chlrhkd4** [comment]
안녕하세요

혹시 전체 메세지 정보를 가지고 계신가요??


2023년 10월 18일 (수) 18:09, byungmeo ***@***.***>님이 작성:

**Comment by byungmeo** [comment]
@chlrhkd4 
내일 주중에 한 번 연락 해보겠습니다.

없는 DLL 파일 Import해도 저렇게 오류는 안뜨는데
재현이 쉽지않네요..
appconfig쪽 문제도 아닌것같고..

**Comment by byungmeo** [comment]
@chlrhkd4 
질문 주신분께 다시 여쭤보니 오류가 갑자기 안나타난다고 하시네요..

**Comment by byungmeo** [comment]
1b656d3b8845f3cd603775393011444b08ed7802

우선 단축키 사용 여부 선택 및 단축키 변경 가능 하도록 변경하였습니다.
하지만, 일시 비활성화의 경우에는 ModifierKeys만 추적 가능해서
결국 거상에서 잘 안쓰는 Alt키로 고정할 수 밖에 없었네요..
해당 키 누름 여부 확인하는 Win32 API(GetAsyncKeyState)가 하나 있긴 하던데
제가 잘 모르는건지.. 생각한대로 작동되지는 않았습니다.
(감지도 잘 안되고.. 키를 누르고 있는 동안 계속해서 true를 반환하진 않더군요)

거상 창 활성화 시에도 단축키가 안먹는 문제는
마찬가지로 GetAsyncKeyState나 키보드 입력 후킹으로 해결할 수 있다 보고 시작했으나
위와 같은 문제 + 보안 상의 문제로 해결이 힘들어 보이네요...ㅜㅜ

타 게임 실행 중 문제는
최소한 타 게임의 마우스 가두기를 방해하지 않는 선에서 마무리 하기로 하였습니다.
다른 가두기 방법이 있어 보이긴 하지만, 지금 케이스는 다른 프로세스를 가두는거다보니 
한계가 있는 것 같네요.
일단 롤은 자기네가 아예 다른 프로세스의 가두기를 먹어(?) 버려서
롤 실행 중엔 거상 스테이션 기능으로 가두기가 좀 힘들어보이네요.

제일 해결하고 싶은 문제만 해결이 힘들게 되었네요 ㅠ

선택한 클라만 가두는 로직은 위에 언급한대로
조만간 완성 할 예정입니다.

취준때매 1.5.1은 많이 늦어질 수도 있겠네요,,

**Comment by chlrhkd4** [comment]
고생많으셨습니다! ㅠㅠ 저도 많이 도움드렸어야 하는데 일때문에 쉽지 않았어요 

감사합니다!
