### ISSUE TITLE
유효성 검사

### ISSUE THREAD

**Issue by byungmeo** [byungmeo/GersangStation#35]
브랜치 Integrity

1. UI 개선
2. ExcludeFile (대소문자) 관련 해결책 찾기
3. 다음 분기패치 시 상세한 테스트

**Comment by chlrhkd4** [comment]
안녕하세요

혹시 대소문자 관련하여 추가 이슈 있는것이 있는지요??

참고로 excludedFile 리스트는 서버에서 가져오는것으로 변경하려고 합니다.


2023년 10월 16일 (월) 10:18, byungmeo ***@***.***>님이 작성:

**Comment by byungmeo** [comment]
@chlrhkd4

안녕하세요
아직 확인은 안 해봐서 시간 날 때 확인해보려고 했습니다.
그 방법으로 해도 좋은것같아요.
