### ISSUE TITLE
유효성 검사 중 거상 클라이언트 켜져있는 상태에서는 비정상 동작

### ISSUE THREAD

**Issue by chlrhkd4** [byungmeo/GersangStation#38]
거상 클라이언트가 켜져있는 상태에서 유효성 검사 진행시 '클라이언트 파일을 읽어오는 중입니다' 에서 더 이상 progress 가 진행되지 않음

유저에게 시작 전에 Notice 를 주거나, 실행중인지 확인하는 step을 추가하여 걸러내야 할 것 같습니다.

**Comment by byungmeo** [comment]
[커밋내역](https://github.com/byungmeo/GersangStation/compare/1.5.1...master)

`ClipMouse.GetAllGameHandles().Count > 0`
좀 야매 같지만 제일 좋은 방법 같네요
수정해서 1.5.1.1로 릴리즈 파일 바꿨습니다~
감사합니다

**Comment by chlrhkd4** [comment]
?! 이런 신박한 방법이 있었군요 ㅎㅎ 감사합니다
